services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8501"
    
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"