services:
  frontend:
    build: 
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "8080:8501"
    volumes:
      - ./app:/app:ro

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api:ro
