services:
  scriballm:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8501"
    environment:
      - GITHUB_REPO=eliaf2/ScribaLLM
      - GITHUB_BRANCH=main

  apimodel:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - GITHUB_REPO=eliaf2/ScribaLLM
      - GITHUB_BRANCH=main